### PR TITLE
std.extVar return null instead of raise an Excpetion

### PR DESCRIPTION
**Pull request by eloycoto**
At the moment the std.extVar raises an exception if the variable does
not exits, this change return null if the variable is not set, the same
behaviour as PR #529

This allows to users to set default variables from outside and the uers
that want to have a error can do a conditional condition.

Usage examples:
```
breo.acalustra.com ➜  jsonnet git:(master) ✗ ./jsonnet -V y=1 -e 'if std.extVar("x") != null then 1'
null
breo.acalustra.com ➜  jsonnet git:(master) ✗ ./jsonnet -V x=1 -e 'if std.extVar("x") != null then 1'
1
breo.acalustra.com ➜  jsonnet git:(master) ✗ ./jsonnet -V y=1 -e 'std.extVar("x")'
null
```

Signed-off-by: Eloy Coto <eloy.coto@gmail.com>
CLA is signed.

### CODE REVIEW

**Comment by seh** [comment]
Since it's possible to supply null as a value, callers then can't distinguish between a value not being set and a value being set to null. Is that acceptable?
```
jsonnet --ext-code v=null --exec '{v: std.extVar("v")}'
{
   "v": null
}
```

**Comment by sbarzowski** [comment]
Please see comments:
- https://github.com/google/jsonnet/issues/316#issuecomment-306069666
- https://github.com/google/jsonnet/issues/316#issuecomment-398604467

This feature would require more discussion.

**Comment by eloycoto** [comment]
thanks @sbarzowski ;-)

**Comment by sparkprime** [comment]
Sorry, it is this way deliberately :)

**Pull request closed without merging**
