### PR TITLE
Add std.mapWithIndex and std.mapWithKey

### PR DESCRIPTION
**Pull request by andreabedini**
`mapWithIndex` and `mapWithKey` are two functions that I always find useful. I am aware of thelist and object comprehension syntax but I tend to use it only for very short fragments of code. Naming is vaguely inspired by Haskell's `Data.Map`.

### CODE REVIEW

**Comment by andreabedini** [comment]
I signed it!

**Comment by sparkprime** [comment]
This looks useful, thanks.  Can you regenerate some of the golden test outputs to account for changed line numbers in stack traces that happen to go through std.jsonnet ?

What you do is:
cd test_suite
./refresh_golden.sh a.jsonnet b.jsonnet ...
until make test (in root of repo) works OK.

thanks

**Comment by sparkprime** [comment]
Also can you add corresponding docs, see https://github.com/google/jsonnet/pull/450/files for an example

**Comment by andreabedini** [comment]
> This looks useful, thanks. Can you regenerate some of the golden test outputs to account for changed line numbers in stack traces that happen to go through std.jsonnet ?

ah! that was the problem, sorry I had little time to investigate before.

> Also can you add corresponding docs, see https://github.com/google/jsonnet/pull/450/files for an example

Will do.

**Comment by sparkprime** [comment]
Thanks

**Pull request merged**
