### PR TITLE
Python 3 compatibility

### LINKED ISSUE #26: Python 3.x Compatibility
I forked and converted to use Visual Studio, and I also changed support from Python 2 C API to Python 3.4 API. It wasn't horribly difficult to do either task, but the project is there for anybody who needs or wants it.

### PR DESCRIPTION
**Pull request by benley**
Fixes #26, #330

### CODE REVIEW

**Comment by benley** [comment]
The one part I'm not sure about in this change is the `m_size` field in the `PyModuleDef _jsonnet` struct.  Does this module keep internal state in a way that requires an allocation here?

**Comment by sparkprime** [comment]
m_size == -1 should be OK because all of the state is built up and torn down within the single evaluate call.  

Thanks for doing this!

**Comment by ant31** [comment]
is it merged ?

**Comment by benley** [comment]
I was wondering that too - maybe the merge happened in piper and we're waiting for MOE or copybara (or something) to run and publish the result back to github?

**Comment by sparkprime** [comment]
I'm afraid the explanation was more simple than that :)  Sorry

**Comment by benley** [comment]
No worries - thanks for merging :-D

**Comment by wiseman** [comment]
Thanks for doing this work!

Is there an ETA for a new pypi release with support for Python 3?

**Comment by sparkprime** [comment]
No plan just yet, if you need it make a bug and we'll figure out if there's anything we should wait for vs just cut it then and there.

**Pull request merged**
