### PR TITLE
Convert site to Jekyll.

### PR DESCRIPTION
**Pull request by davidzchen**
* Converted Jsonnet website to Jekyll.
* Add tooling for building the Jekyll tree, bringing up the site
  locally, and pushing a new version of the site to gh-pages
* Add page to redirect users to new URL.

This is a pretty huge diff. It may be easier to digest by looking at the `site` branch on my fork: https://github.com/davidzchen/jsonnet/tree/site

The motivation for using Jekyll is that it is the [official static site generator that is supported by GitHub](https://help.github.com/articles/using-jekyll-with-pages/). With this new pipeline, the Jsonnet website will be served out of https://google.github.io/jsonnet rather than https://google.github.io/jsonnet/doc

The way the new pipeline for publishing the site works is the following (see `tools/scripts/push_docs.sh`):

1. Build a zip containing the Jekyll tree constructed from all files under `doc/` and the included Jsonnet files from `examples/` and `benchmarks/`.
2. In a separate directory (either specified via argument to the script) clone the Jsonnet repository, `git checkout gh-pages`
3. Replace the content of the repository with the contents of the zip archive containing the new version of the site.
4. Commit and push.

I have also added a script that just builds the Jekyll tree, unzips it in a temp directory, and runs `jekyll serve`, which will bring up the site locally, viewable at `http://localhost:4000`.

### CODE REVIEW

**Comment by davidzchen** [comment]
Rebased and resolved merge conflicts.

**Comment by sparkprime** [comment]
Thanks.  I'm in favor of this but I need to understand better what you've actually done here.  We should talk about it face to face next week.

**Comment by davidzchen** [comment]
Sounds good to me.

**Comment by davidzchen** [comment]
I have rebased this patch and added pages to redirect users visiting the pages at the old URL to the new locations for the pages. I have all the pages locally.

**Comment by sparkprime** [comment]
This is all good, you should merge it when you're comfortable doing so

**Pull request merged**
