### PR TITLE
Fix swapped indexes in spec (object-inherit)

### PR DESCRIPTION
**Pull request by sbarzowski**
q is the number of assertions on the right side
p is the number of fields that exist on left side and not on the right
side
r is the number of fields that exist on right side and not on the left
side

### CODE REVIEW

**Comment by sbarzowski** [comment]
@sparkprime

**Comment by sparkprime** [comment]
The f's need apostrophes too.

**Comment by sparkprime** [comment]
As do the h's and the e's :)

**Comment by sbarzowski** [comment]
done

**Pull request merged**
