### PR TITLE
Install RUNTIME files of shared libraries

### PR DESCRIPTION
**Pull request by podsvirov**
The DLL part of a shared library is treated as a RUNTIME target for DLL platforms (all Windows-based systems including Cygwin).

### CODE REVIEW

**Comment by podsvirov** [comment]
Ping.

**Comment by podsvirov** [comment]
Ping.

**Comment by johnbartholomew** [comment]
Hi. Thanks for your contribution, and your patience! This looks good - I expect to merge (*) it shortly.

(* actually rebase)

**Comment by johnbartholomew** [comment]
Now in master as commit https://github.com/google/jsonnet/commit/4e7678a907c273cbb6f7554f3ce53eee59aab778

Looks like GitHub's detection of merges didn't realise it is from this PR though, so I'll close this manually.

**Pull request closed without merging**
