### PR TITLE
Fixup for USE_SYSTEM_JSON=ON/OFF compatibility

### PR DESCRIPTION
**Pull request by podsvirov**

### CODE REVIEW

**Comment by podsvirov** [comment]
Ping.

**Comment by podsvirov** [comment]
Ping.

**Comment by johnbartholomew** [comment]
Hi. Thanks for your contribution, and your patience! This looks good - I expect to merge (*) it shortly.

(* actually rebase)

**Comment by johnbartholomew** [comment]
Now in master as commit https://github.com/google/jsonnet/commit/a4aeb1d05c6e63cfe219d76c83f4174d7903313e

Looks like GitHub's detection of merges didn't realise it is from this PR though, so I'll close this manually.

**Pull request closed without merging**
