### PR TITLE
Add Windows support for Travis CI

### LINKED ISSUE #734: Publish binary releases for Windows
It would be great to have binary releases also for Windows.

Related to #109

### PR DESCRIPTION
**Pull request by mckunda**
DO NOT MERGE UNTIL SECURITY PROBLEMS ARE RESOLVED!

Fixes #734 

This PR is an attempt to provide Windows builds as proposed at #734

Prerequisites:
* chocolatey
* llvm ([Travis uses v9.0.0](https://docs.travis-ci.com/user/reference/windows#pre-installed-chocolatey-packages))
* make (install using `choco install make`)

Build:
```
refreshenv
cmake . -B build -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -G "Unix Makefiles"
cmake --build build --target jsonnetfmt
cmake --build build --target jsonnet
cmake --build build --target run_tests
```

.travis.yml is modified so that archives with executables can be found at directory `upload`

Problems:
* `-pedantic` leads to compiler errors since MSVC libraries use language extensions
* `-std=c++11` leads to compiler errors
* unable to run `setup.py`
* unable to run regression tests (CMake target `run_tests`, file`test_suite/run_tests.sh`)
* [Secrets ARE NOT obfuscated in Travis Windows builds](https://travis-ci.community/t/current-known-issues-please-read-this-before-posting-a-new-topic/264) (means this PR is unable to merge)

Any support is appreciated.

### CODE REVIEW

**Comment by Toilal** [comment]
https://github.com/mcovalt/jsonnetbin just works and seems damn simple. Please take a look at this repository and include the setup.py configuration inside the official project.

**Review by lastthyme — APPROVED** [review]

**Comment by johnbartholomew** [comment]
Hi! Thanks for your contribution, and your patience!

The Travis CI build unfortunately stopped working a while ago (I'm not sure exactly when), so this PR in its current form is no longer viable. However we now GitHub actions workflow to replace it, so hopefully we can set up something that will satisfy #734 

> https://github.com/mcovalt/jsonnetbin just works and seems damn simple. Please take a look at this repository and include the setup.py configuration inside the official project.

That repository is not accessible to me - perhaps the author has deleted it or made it private. I see they left a comment https://github.com/google/jsonnet/issues/734#issuecomment-634846921 that gives a hint at what they did though. I also see you (@Toilal) have a package derived from jsonnetbin at https://github.com/Toilal/python-jsonnet-binary

**Comment by mckunda** [comment]
Ok, closing as irrelevant.

**Comment by johnbartholomew** [comment]
@mckunda FYI, if you are still interested in Windows support for the Python module, I am hoping that #1137 will get us significantly closer to that.

**Pull request closed without merging**
