### PR TITLE
Improve performance of repeated same file import

### PR DESCRIPTION
**Pull request by sparkprime**
@huggsboson

### CODE REVIEW

**Comment by huggsboson** [comment]
lgtm

**Comment by sparkprime** [comment]
Related (coincedentally) #239

**Comment by sparkprime** [comment]
@fare this just caches the parsed, analyzed, desugared AST but gave a 2x boost in a real usecase.

**Comment by sparkprime** [comment]
Travis on osx is giving a weird error but it seems unrelated to jsonnet so I'm committing anyway.

**Comment by fare** [comment]
Can you cache the expression, so the value is shared, too?

**Pull request merged**
