### PR TITLE
Add windows build support

### LINKED ISSUE #476: PIP install failing on Windows 10
I am having trouble installing the jsonnet python package. In particular the build step is failing. Here is my output from pip

```
C:\Python27\Scripts>pip install jsonnet
Collecting jsonnet
  Using cached jsonnet-0.10.0.tar.gz
Installing collected packages: jsonnet
  Running setup.py install for jsonnet ... error
    Complete output from command C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\me\\appdata\\local\\temp\\pip-build-i148_p\\jsonnet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\me\appdata\local\temp\pip-4njvtc-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    error: [Error 2] The system cannot find the file specified

    ----------------------------------------
Command "C:\Python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\me\\appdata\\local\\temp\\pip-build-i148_p\\jsonnet\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record c:\users\me\appdata\local\temp\pip-4njvtc-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\me\appdata\local\temp\pip-build-i148_p\jsonnet\
```

I have run the pip install command in the Visual Studio 2017 and Visual Studio 2015 command prompt with python tools installed and received the same error. I also tried installing MinGW, added its bin folder to my path, and specified in the distutils.cfg to use the mingw32 compiler (as seen below) with no success.

_Distutils.cfg_
```
[build]
compiler = mingw32

[build_ext]
compiler = mingw32
```

I also tried downloading the tar directly from here and running the build command below and received the same error.

```
C:\Python27\python.exe setup.py build
running build
running build_ext
error: [Error 2] The system cannot find the file specified
```

I'm not sure what else to try. Are there wheels available for windows?

Thanks,

Bert

### PR DESCRIPTION
**Pull request by Toilal**
This should fix #476 and is a first step for #734 by fixing CMake.

With this PR, python extension build is now performed by either CMake, make or distutils compiler using a fallback strategy. (It will try using CMake first, then make, and fallback to distutils compiler).

CMake has been modifier to accept the build to run with MSVC compilet (tested on Windows with Visual C++ Build Tools v14.2)

Here's the command to run on windows to build.

```
cmake . -Bbuild && cmake --build build --config Release
```

Release files are then available in `build/Release`

There's still linker errors when, but exe files are available and works properly, any help welcome about those errors (I'm not a C/C++ developer). (maybe it's related to #778)

```
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_version rÚfÚrencÚ dans la fonction "public: static class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >__cdecl jsonnet::Jsonnet::version(void)" (?version@Jsonnet@jsonnet@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_make rÚfÚrencÚ dans la fonction "public: bool __cdecl jsonnet::Jsonnet::init(void)" (?init@Jsonnet@jsonnet@@QEAA_NXZ) [C:\Users\xxx\p rojects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_max_stack rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::setMaxStack(unsigned int)" (?setMaxStack@Jsonnet@jsonnet@@QEAA XI@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_gc_min_objects rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::setGcMinObjects(unsigned int)" (?setGcMinObjects@Jsonnet@ jsonnet@@QEAAXI@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_gc_growth_trigger rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::setGcGrowthTrigger(double)" (?setGcGrowthTrigger@Jsonn et@jsonnet@@QEAAXN@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_string_output rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::setStringOutput(bool)" (?setStringOutput@Jsonnet@jsonnet@@ QEAAX_N@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_ext_var rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::bindExtVar(class std::basic_string<char,struct std::char_traits< char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?bindExtVar@Jsonnet@jsonnet@@QEAAXAEBV?$basic_string@DU?$char_trai ts@D@std@@V?$allocator@D@2@@std@@0@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_ext_code rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::bindExtCodeVar(class std::basic_string<char,struct std::char_tr aits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?bindExtCodeVar@Jsonnet@jsonnet@@QEAAXAEBV?$basic_string@DU?$ char_traits@D@std@@V?$allocator@D@2@@std@@0@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_tla_var rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::bindTlaVar(class std::basic_string<char,struct std::char_traits< char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?bindTlaVar@Jsonnet@jsonnet@@QEAAXAEBV?$basic_string@DU?$char_trai ts@D@std@@V?$allocator@D@2@@std@@0@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_tla_code rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::bindTlaCodeVar(class std::basic_string<char,struct std::char_tr aits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?bindTlaCodeVar@Jsonnet@jsonnet@@QEAAXAEBV?$basic_string@DU?$ char_traits@D@std@@V?$allocator@D@2@@std@@0@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_max_trace rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::setMaxTrace(unsigned int)" (?setMaxTrace@Jsonnet@jsonnet@@QEAA XI@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_jpath_add rÚfÚrencÚ dans la fonction "public: void __cdecl jsonnet::Jsonnet::addImportPath(class std::basic_string<char,struct std::char_tr aits<char>,class std::allocator<char> > const &)" (?addImportPath@Jsonnet@jsonnet@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libj sonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_evaluate_file rÚfÚrencÚ dans la fonction "public: bool __cdecl jsonnet::Jsonnet::evaluateFile(class std::basic_string<char,struct std::char _traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?evaluateFile@Jsonnet@jsonnet@@QEAA_NAEBV?$basic_string@DU?$char _traits@D@std@@V?$allocator@D@2@@std@@PEAV34@@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_evaluate_snippet rÚfÚrencÚ dans la fonction "public: bool __cdecl jsonnet::Jsonnet::evaluateSnippet(class std::basic_string<char,struct std ::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?evaluateSnippet@Jsonnet@jsonnet@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0PEAV34@@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjso nnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_evaluate_file_multi rÚfÚrencÚ dans la fonction "public: bool __cdecl jsonnet::Jsonnet::evaluateFileMulti(class std::basic_string<char,struc t std::char_traits<char>,class std::allocator<char> > const &,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::ch ar_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_s tring<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > *)" (?evaluateFileMulti@Jsonnet@jsonn et@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocat or@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@4@@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_evaluate_snippet_multi rÚfÚrencÚ dans la fonction "public: bool __cdecl jsonnet::Jsonnet::evaluateSnippetMulti(class std::basic_string<char ,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::map<class std::basic_string<char, struct std::char_traits<char>,class std::allocator<char> >,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,struct std::less<class std::basic_string<char,struct std::cha r_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char, struct std::char_traits<char>,class std::allocator<char> > > > > *)" (?evaluateSnippetMulti@Jsonnet@jsonnet@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0PEAV?$map@V?$basic_string@D U?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@ @V12@@std@@@2@@4@@Z) [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
libjsonnet++.obj : error LNK2019: symbole externe non rÚsolu jsonnet_destroy rÚfÚrencÚ dans la fonction "public: __cdecl jsonnet::Jsonnet::~Jsonnet(void)" (??1Jsonnet@jsonnet@@QEAA@XZ) [C:\Users\xxx\pro jects\jsonnet\build\cpp\libjsonnet++.vcxproj]
C:\Users\xxx\projects\jsonnet\build\Release\jsonnet++.dll : fatal error LNK1120: 17 externes non rÚsolus [C:\Users\xxx\projects\jsonnet\build\cpp\libjsonnet++.vcxproj]
```

### CODE REVIEW

**Comment by Toilal** [comment]
I also need help to fix the python extension build on CI. It was OK on my Ubuntu machine with both Python 2.7 and Python 3.8. On TravisCI, it seems we need to bring some flags from Makefile into the setuptools compiler abstraction.

**Comment by Toilal** [comment]
Ok, build is now OK on CI, but tests are failing to load :(. Again, it works on my computer (python setup.py test)

**Comment by sparkprime** [comment]
Those linker errors are for the C++ wrapper which I think it doesn't make sense to build into a DLL because of the binary incompatibility between different C++ compilers.

**Review by jmarrr — APPROVED** [review]

**Comment by Toilal** [comment]
https://github.com/mcovalt/jsonnetbin just works and seems damn simple. Please take a look at this repository and include the setup.py configuration inside the official project.

**Pull request closed without merging**
