### PR TITLE
Hexfloat support for parser; formatter

### PR DESCRIPTION
**Pull request by jwise**
This pull request has two independent commits to add support for hexfloats each to the output formatter and to the parser.  (This is an implementation of #499.)  There are tests available for the parser.  It fairly trivially passes hexfloat support back to the C++11 back end, which has native support.  

We anticipate heavily using the hexfloat-input support, whereas the hexfloat-output support would be "nice to have" for our use cases.

### CODE REVIEW

**Comment by jwise** [comment]
Hmm, the compilers that Travis is using on Linux are _really_ old.  I'll fix the stderr issue in the morning ... and I'll also have a look at the CLA issue in the morning too (I have it all signed, but there might need to be further diagnostics).  Any chance we could get the Travis compiler version on Linux bumped to something more modern?

**Comment by jwise** [comment]
@googlebot I signed it!

**Comment by jwise** [comment]
Ping @sparkprime .  Would be interested to know if any parts of this would be accepted upstream -- we'd really like to avoid having to maintain an internal branch!

**Comment by sparkprime** [comment]
Sorry for the delay.  So in C++ it's quite easy to parse a hexfloat, but what about Go?

**Comment by sparkprime** [comment]
Basically I'm ok with extending the language to allow people to configure things very precisely (with hexfloats) as long as it doesn't make the language overly difficult to implement.

**Comment by sparkprime** [comment]
As for the output, a global switch doesn't feel quite right.  We should look into the custom manifesting approach and see if it can be made to work.  An alternative is to use a native function to do the manifesting.  And also it seems as long as you're not losing precision with the decimal output, and if it's just for machine reading, maybe you don't need it at all.

**Comment by sparkprime** [comment]
I found this: https://github.com/golang/go/issues/125

**Comment by sparkprime** [comment]
Oh and the fact that we get hex integers for free with this is pretty cool

**Comment by jwise** [comment]
Sorry for the delay.

I agree that "probably" we do not need hexfloat manifest support (though, perversely, the thing that seems the least useful is also the thing that is the least pain to implement, because it does not force itself on the golang implementation).

I did notice that Go does not have native hexfloat input support.  golang/go#12518 is better than last I checked, which was when I saw the "output" form of hexfloat, golang/go#8072, in which the Go team saw a user request and summarily gave the friendly response of "Not worth doing."

Thinking about it, it should not be terribly difficult to implement, especially limited to the "normalized" form (0x1.[...]p[...]); one could first (trivially) parse the mantissa, convert that to a double, and then add the exponent.  If one so desired to support denormals perfectly, it would be slightly more difficult, but not at all impossible.  So this should be very doable in Go, even in versions of Go that are not yet in the future.

**Comment by sparkprime** [comment]
Closing this until we have a Golang solution. In all likelyhood we will deprecate the C++ solution before Go supports this though!

**Pull request closed without merging**
