### PR TITLE
Update libjsonnet++.h - fixed typo 'carbage collection' to 'garbage collection'

### PR DESCRIPTION
**Pull request by jiakuan**
Typo correction: carbage => garbage

### CODE REVIEW

**Comment by sbarzowski** [comment]
Thanks!

Could you sign the CLA and make the commit message more specific?

**Comment by jiakuan** [comment]
> Thanks!
> 
> Could you sign the CLA and make the commit message more specific?

Already signed the CLA. Also changed the pull request title.

**Comment by sbarzowski** [comment]
@googlebot

**Comment by sbarzowski** [comment]
Thanks!

**Pull request merged**
